### ISSUE TITLE
[FEATURE] Synchronize avatar

### ISSUE THREAD

**Issue by echavaillaz** [xperseguers/t3ext-causal_accounts#7]
Hi,

Since TYPO3 7.4, backend users have the possibility to add an avatar to their profile. It would be great that causal_accounts takes care of it during the synchronization.

Thanks!

**Comment by jbhemmer** [comment]
+1

**Comment by xperseguers** [comment]
Instead of synchronizing avatars, it may be wise to rely on this newly added feature instead: https://forge.typo3.org/issues/68429

**Comment by echavaillaz** [comment]
Yes of course...

**Comment by xperseguers** [comment]
In order to KISS, this won't be implemented. Instead, I suggest to rely on use Gravatar (much cooler and always up-to-date anyway) with t3gravatar: https://typo3.org/extensions/repository/view/t3gravatar
